version: '3'

services:
  axispostgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:5432"
    # volumes:
    # Alterar essa informação para funcionar em sua máquina caso deseje persistir o banco de dados
      # - ./axis_data/PostgreSQL:/var/lib/postgresql/data
    networks:
      - local

  axispostgrestest:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_TEST_PORT}:5432"
    networks:
      - local

  axisapi:
    build: .
    depends_on:
      - axispostgres
      - axispostgrestest
    ports:
      - "80:3000"
    environment:
      POSTGRES_HOST: axispostgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
      SERVE_FILE_PATH: http://[::1]/images
    networks:
      - local
    volumes:
    # Alterar essa informação para funcionar em sua máquina caso deseje persistir o banco de dados
      - ./data/images:/_upload
    

networks:
  local:
    driver: bridge
